// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC33I7CUJ-IpDcezgkpTXkFhZWva-mAhvI',
    appId: '1:613254671357:android:d00f9187302f44ad948794',
    messagingSenderId: '613254671357',
    projectId: 'zolaapp-2895a',
    databaseURL: 'https://zolaapp-2895a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zolaapp-2895a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbltcfa_jMR0ZAyYXQr7q0pWPJNmArdEs',
    appId: '1:613254671357:ios:99c11a68711fb64e948794',
    messagingSenderId: '613254671357',
    projectId: 'zolaapp-2895a',
    databaseURL: 'https://zolaapp-2895a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zolaapp-2895a.firebasestorage.app',
    androidClientId: '613254671357-98bfkk5165mqad5tcrua8h63km73tnrs.apps.googleusercontent.com',
    iosClientId: '613254671357-07jmt07mnf7hs1rpummfg9fahd0lph8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );
}
